name: build hugo

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'

      - name: Build
        run: hugo --minify
      
      - name: Render
        uses: actions/upload-artifact@v2
        with: 
          name: rendered-html
          path: ./public

      - name: Checkout GitHub Pages Branch
        uses: actions/checkout@v2
        with:
          repository: "${GITHUB_ACTOR}/moeb98.github.io"
          ref: "master"
          path: "gh-pages"
      - name: Copy to GitHub Pages
        run: |
          rm -rf gh-pages/*
          cp -Rv ./public/* gh-pages/
      - name: Commit
        working-directory: ./gh-pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update docs"
      - name: Push
        working-directory: ./gh-pages
        run: |
          REMOTE="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/moeb98.github.io.git"
          git push "${REMOTE}"
